### ISSUE TITLE
Huge performance impact of SeoCollector

### ISSUE THREAD

**Issue by j0r1s** [agence-adeliom/easy-seo-bundle#2]
The collector is used in admin, where I have a lot of blocks from easy-editor-bundle.

The scrapping takes a huge amount of time on this page and basically makes the admin unusable : 
<img width="841" alt="image" src="https://user-images.githubusercontent.com/35805130/211821547-bbf3a02d-ab31-451e-b7af-13585df0919f.png">

As a workaround, I'm returning early in the collect function when request path starts with `/admin` : 
```php
if (strpos($request->getPathInfo(), '/admin') === 0) {
    return;
}
```

**Comment by arnaud-ritti** [comment]
Hi, 

I have added options to the configuration in the latest version:

```yaml
# config/packages/easy_seo.yaml
easy_seo:
  ...
  enable_profiler: '%kernel.debug%'
  ignore_profiler: 
    - '^/admin*'
```

it should fix the issue
